import {
  Button,
  Form,
  FormItem,
  Input,
  Message,
  Table,
  TableColumn,
  Popover,
  Dialog,
  DatePicker,
  Tooltip,
  Upload,
  MessageBox,
  Autocomplete,
  Empty,
} from 'element-ui';

export default {
  [Button.name]: Button,
  [Form.name]: Form,
  [FormItem.name]: FormItem,
  [Input.name]: Input,
  [Table.name]: Table,
  [TableColumn.name]: TableColumn,
  [Popover.name]: Popover,
  [Dialog.name]: Dialog,
  [DatePicker.name]: DatePicker,
  [Tooltip.name]: Tooltip,
  [Upload.name]: Upload,
  [Autocomplete.name]: Autocomplete,
  [Empty.name]: Empty,
  Message,
  MessageBox
};
